### ISSUE TITLE
Allow basing a simulated device in another

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pyvisa-sim#16]
It is common that multiple devices will share a large part of the commands. Here, we propose a syntax to facilitate this.

We will add to the device dict a new key (`bases`) with the value specifying a list of devices used as bases. Multiple bases are allowed. Bases first in the list have precedence.

Each element of the list is dictionary specifying the device like it is done in the [resources](http://pyvisa-sim.readthedocs.org/en/latest/definitions.html#resources) section.

```
    <device name>:
        bases: 
             - device: base 1
             - device: base 2
               filename: myfile.yaml
             - device: base 3
               filename: default.yaml
               bundled: true
        <here goes the device definition>
```

#### Implementation

For each base, its dictionary is loaded and merged with the derived device.
