### ISSUE TITLE
Add support for instrument with channels.

### ISSUE THREAD

**Issue by MatthieuDartiailh** [hgrecco/pyvisa-sim#9]
I think the idea would simply be to store the parameters in different dictionaries according to the channel. Two main mechanism should supported :
- the active channel is defined through a command
- the channel is specified as part of the command (the string parser might be of help here).

**Comment by hgrecco** [comment]
Agreed. Maybe the way is to add a `channels`  entry in the property dict and require that getters and setters are written with named placeholders such as `{channel:d}` and `{value:.3f}`

I will release version 0.1 later this week and start with this afterwards.

**Comment by MatthieuDartiailh** [comment]
It might be better to keep track of the channels at the instrument level rather that at the property level, as often instruments have many (a dozen) property which apply to channel. Could you do some hierarchical declaration in the YAML like this:
``` yaml
device PNA:
    properties : 
         # instrument wide properties
    channel :
         properties:
              # channel specific declaration.
```
Otherwise I fine with the use of '{channel}' or '{ch_id}' (may make sense to use the same we may use in lantz, whatever it ends to be).
